import { Player, PlayerPosition } from '../app/types/game';
import { calculatePlayerPrice } from './pricing';

const rawPlayers = [
  { id: 'hulk', name: 'Hulk', overall: 84, position: 'FW', nationality: 'Brazil', club: 'Atlético Mineiro', attributes: { pace: 80, shooting: 86, passing: 81, dribbling: 82, defending: 42, physical: 89 } },
  { id: 'cano', name: 'Germán Cano', overall: 83, position: 'FW', nationality: 'Argentina', club: 'Fluminense', attributes: { pace: 72, shooting: 87, passing: 68, dribbling: 77, defending: 35, physical: 76 } },
  { id: 'borja', name: 'Miguel Borja', overall: 81, position: 'FW', nationality: 'Colombia', club: 'River Plate', attributes: { pace: 74, shooting: 82, passing: 65, dribbling: 72, defending: 32, physical: 80 } },
  { id: 'pedro', name: 'Pedro', overall: 83, position: 'FW', nationality: 'Brazil', club: 'Flamengo', attributes: { pace: 73, shooting: 85, passing: 72, dribbling: 80, defending: 38, physical: 79 } },
  { id: 'cavani', name: 'Edinson Cavani', overall: 82, position: 'FW', nationality: 'Uruguay', club: 'Boca Juniors', attributes: { pace: 71, shooting: 83, passing: 70, dribbling: 75, defending: 48, physical: 77 } },
  { id: 'valencia', name: 'Enner Valencia', overall: 80, position: 'FW', nationality: 'Ecuador', club: 'Internacional', attributes: { pace: 82, shooting: 80, passing: 69, dribbling: 76, defending: 38, physical: 78 } },
  { id: 'estevao', name: 'Estêvão', overall: 80, position: 'FW', nationality: 'Brazil', club: 'Palmeiras', attributes: { pace: 85, shooting: 78, passing: 76, dribbling: 84, defending: 30, physical: 62 } },
  { id: 'merentiel', name: 'Miguel Merentiel', overall: 79, position: 'FW', nationality: 'Uruguay', club: 'Boca Juniors', attributes: { pace: 78, shooting: 80, passing: 68, dribbling: 74, defending: 40, physical: 75 } },
  { id: 'j-santos', name: 'Junior Santos', overall: 79, position: 'FW', nationality: 'Brazil', club: 'Botafogo', attributes: { pace: 84, shooting: 78, passing: 70, dribbling: 78, defending: 35, physical: 82 } },
  { id: 'l-henrique', name: 'Luiz Henrique', overall: 82, position: 'FW', nationality: 'Brazil', club: 'Botafogo', attributes: { pace: 87, shooting: 77, passing: 74, dribbling: 83, defending: 45, physical: 77 } },
  { id: 'colidio', name: 'Facundo Colidio', overall: 77, position: 'FW', nationality: 'Argentina', club: 'River Plate', attributes: { pace: 79, shooting: 76, passing: 71, dribbling: 77, defending: 38, physical: 70 } },
  { id: 'calleri', name: 'Jonathan Calleri', overall: 81, position: 'FW', nationality: 'Argentina', club: 'São Paulo', attributes: { pace: 71, shooting: 80, passing: 64, dribbling: 73, defending: 42, physical: 85 } },
  { id: 'silvera', name: 'Maximiliano Silvera', overall: 76, position: 'FW', nationality: 'Uruguay', club: 'Peñarol', attributes: { pace: 75, shooting: 77, passing: 66, dribbling: 72, defending: 36, physical: 73 } },
  { id: 'arrascaeta', name: 'G. De Arrascaeta', overall: 84, position: 'MF', nationality: 'Uruguay', club: 'Flamengo', attributes: { pace: 72, shooting: 81, passing: 86, dribbling: 84, defending: 45, physical: 68 } },
  { id: 'ganso', name: 'Ganso', overall: 80, position: 'MF', nationality: 'Brazil', club: 'Fluminense', attributes: { pace: 50, shooting: 74, passing: 87, dribbling: 82, defending: 48, physical: 65 } },
  { id: 'alan-patrick', name: 'Alan Patrick', overall: 82, position: 'MF', nationality: 'Brazil', club: 'Internacional', attributes: { pace: 68, shooting: 79, passing: 84, dribbling: 82, defending: 50, physical: 70 } },
  { id: 'de-la-cruz', name: 'Nicolás De La Cruz', overall: 83, position: 'MF', nationality: 'Uruguay', club: 'Flamengo', attributes: { pace: 80, shooting: 78, passing: 82, dribbling: 81, defending: 70, physical: 75 } },
  { id: 'garro', name: 'Rodrigo Garro', overall: 81, position: 'MF', nationality: 'Argentina', club: 'Corinthians', attributes: { pace: 74, shooting: 79, passing: 83, dribbling: 81, defending: 55, physical: 71 } },
  { id: 'lucas-moura', name: 'Lucas Moura', overall: 82, position: 'MF', nationality: 'Brazil', club: 'São Paulo', attributes: { pace: 85, shooting: 78, passing: 77, dribbling: 83, defending: 48, physical: 72 } },
  { id: 'zenon', name: 'Kevin Zenón', overall: 78, position: 'MF', nationality: 'Argentina', club: 'Boca Juniors', attributes: { pace: 81, shooting: 74, passing: 77, dribbling: 79, defending: 62, physical: 70 } },
  { id: 'veiga', name: 'Raphael Veiga', overall: 83, position: 'MF', nationality: 'Brazil', club: 'Palmeiras', attributes: { pace: 75, shooting: 82, passing: 82, dribbling: 80, defending: 52, physical: 72 } },
  { id: 'arias', name: 'Jhon Arias', overall: 82, position: 'MF', nationality: 'Colombia', club: 'Fluminense', attributes: { pace: 84, shooting: 76, passing: 79, dribbling: 82, defending: 58, physical: 70 } },
  { id: 'gerson', name: 'Gerson', overall: 81, position: 'MF', nationality: 'Brazil', club: 'Flamengo', attributes: { pace: 73, shooting: 75, passing: 80, dribbling: 82, defending: 68, physical: 79 } },
  { id: 'almada', name: 'Thiago Almada', overall: 81, position: 'MF', nationality: 'Argentina', club: 'Botafogo', attributes: { pace: 82, shooting: 76, passing: 80, dribbling: 83, defending: 40, physical: 61 } },
  { id: 'vidal', name: 'Arturo Vidal', overall: 79, position: 'MF', nationality: 'Chile', club: 'Colo-Colo', attributes: { pace: 62, shooting: 75, passing: 77, dribbling: 74, defending: 78, physical: 82 } },
  { id: 'gomez', name: 'Gustavo Gómez', overall: 83, position: 'DF', nationality: 'Paraguay', club: 'Palmeiras', attributes: { pace: 68, shooting: 54, passing: 65, dribbling: 62, defending: 84, physical: 85 } },
  { id: 'thiago-silva', name: 'Thiago Silva', overall: 84, position: 'DF', nationality: 'Brazil', club: 'Fluminense', attributes: { pace: 60, shooting: 52, passing: 73, dribbling: 69, defending: 85, physical: 78 } },
  { id: 'paulo-diaz', name: 'Paulo Díaz', overall: 80, position: 'DF', nationality: 'Chile', club: 'River Plate', attributes: { pace: 72, shooting: 48, passing: 68, dribbling: 64, defending: 81, physical: 80 } },
  { id: 'f-bruno', name: 'Fabrício Bruno', overall: 79, position: 'DF', nationality: 'Brazil', club: 'Flamengo', attributes: { pace: 78, shooting: 40, passing: 60, dribbling: 58, defending: 80, physical: 81 } },
  { id: 'rojo', name: 'Marcos Rojo', overall: 78, position: 'DF', nationality: 'Argentina', club: 'Boca Juniors', attributes: { pace: 64, shooting: 55, passing: 66, dribbling: 60, defending: 78, physical: 80 } },
  { id: 'piquerez', name: 'Joaquín Piquerez', overall: 80, position: 'DF', nationality: 'Uruguay', club: 'Palmeiras', attributes: { pace: 79, shooting: 68, passing: 75, dribbling: 76, defending: 77, physical: 78 } },
  { id: 'arana', name: 'Guilherme Arana', overall: 81, position: 'DF', nationality: 'Brazil', club: 'Atlético Mineiro', attributes: { pace: 80, shooting: 69, passing: 76, dribbling: 77, defending: 76, physical: 75 } },
  { id: 'barboza', name: 'Alexander Barboza', overall: 78, position: 'DF', nationality: 'Argentina', club: 'Botafogo', attributes: { pace: 65, shooting: 45, passing: 61, dribbling: 59, defending: 79, physical: 84 } },
  { id: 'advincula', name: 'Luis Advíncula', overall: 77, position: 'DF', nationality: 'Peru', club: 'Boca Juniors', attributes: { pace: 86, shooting: 62, passing: 69, dribbling: 72, defending: 73, physical: 79 } },
  { id: 'weverton', name: 'Weverton', overall: 82, position: 'GK', nationality: 'Brazil', club: 'Palmeiras', attributes: { pace: 81, shooting: 79, passing: 76, dribbling: 83, defending: 50, physical: 80 } },
  { id: 'armani', name: 'Franco Armani', overall: 81, position: 'GK', nationality: 'Argentina', club: 'River Plate', attributes: { pace: 80, shooting: 78, passing: 72, dribbling: 82, defending: 48, physical: 79 } },
  { id: 'romero', name: 'Sergio Romero', overall: 80, position: 'GK', nationality: 'Argentina', club: 'Boca Juniors', attributes: { pace: 78, shooting: 77, passing: 73, dribbling: 81, defending: 45, physical: 78 } },
  { id: 'rossi', name: 'Agustín Rossi', overall: 81, position: 'GK', nationality: 'Argentina', club: 'Flamengo', attributes: { pace: 81, shooting: 79, passing: 70, dribbling: 82, defending: 46, physical: 77 } },
  { id: 'john', name: 'John', overall: 79, position: 'GK', nationality: 'Brazil', club: 'Botafogo', attributes: { pace: 78, shooting: 77, passing: 71, dribbling: 80, defending: 44, physical: 76 } },
  { id: 'rochet', name: 'Sergio Rochet', overall: 81, position: 'GK', nationality: 'Uruguay', club: 'Internacional', attributes: { pace: 80, shooting: 80, passing: 74, dribbling: 81, defending: 48, physical: 79 } },
  { id: 'fariñez', name: 'Wuilker Fariñez', overall: 72, position: 'GK', nationality: 'Venezuela', club: 'Caracas', attributes: { pace: 74, shooting: 70, passing: 65, dribbling: 73, defending: 40, physical: 68 } },
  { id: 'grando', name: 'Gabriel Grando', overall: 72, position: 'GK', nationality: 'Brazil', club: 'Grêmio', attributes: { pace: 72, shooting: 71, passing: 64, dribbling: 73, defending: 38, physical: 70 } },
  { id: 'lollo', name: 'Luciano Lollo', overall: 72, position: 'DF', nationality: 'Argentina', club: 'Estudiantes', attributes: { pace: 52, shooting: 42, passing: 58, dribbling: 54, defending: 73, physical: 75 } },
  { id: 'm-suarez', name: 'Martín Suárez', overall: 69, position: 'DF', nationality: 'Uruguay', club: 'River Plate', attributes: { pace: 68, shooting: 35, passing: 55, dribbling: 53, defending: 69, physical: 71 } },
  { id: 'boselli', name: 'Sebastián Boselli', overall: 72, position: 'DF', nationality: 'Uruguay', club: 'River Plate', attributes: { pace: 71, shooting: 38, passing: 59, dribbling: 57, defending: 73, physical: 74 } },
  { id: 'j-medina', name: 'Cristian Medina', overall: 74, position: 'MF', nationality: 'Argentina', club: 'Boca Juniors', attributes: { pace: 75, shooting: 67, passing: 74, dribbling: 76, defending: 66, physical: 72 } },
  { id: 'rios', name: 'Richard Ríos', overall: 75, position: 'MF', nationality: 'Colombia', club: 'Palmeiras', attributes: { pace: 78, shooting: 68, passing: 73, dribbling: 78, defending: 65, physical: 76 } },
  { id: 'paez', name: 'Kendry Páez', overall: 74, position: 'MF', nationality: 'Ecuador', club: 'Ind. del Valle', attributes: { pace: 76, shooting: 72, passing: 75, dribbling: 77, defending: 48, physical: 60 } },
  { id: 'endrick', name: 'Endrick', overall: 75, position: 'FW', nationality: 'Brazil', club: 'Palmeiras', attributes: { pace: 84, shooting: 76, passing: 68, dribbling: 77, defending: 35, physical: 78 } },
  { id: 'lucero', name: 'Juan Martín Lucero', overall: 75, position: 'FW', nationality: 'Argentina', club: 'Fortaleza', attributes: { pace: 73, shooting: 76, passing: 66, dribbling: 71, defending: 38, physical: 74 } },
  { id: 'osorio', name: 'Darío Osorio', overall: 73, position: 'FW', nationality: 'Chile', club: 'U. de Chile', attributes: { pace: 80, shooting: 72, passing: 68, dribbling: 74, defending: 35, physical: 65 } },
  { id: 'ebarlin', name: 'Erwin Ebarlin', overall: 64, position: 'FW', nationality: 'Bolivia', club: 'Bolivar', attributes: { pace: 70, shooting: 62, passing: 54, dribbling: 60, defending: 28, physical: 62 } },
  { id: 'silveira-h', name: 'Hugo Silveira', overall: 63, position: 'FW', nationality: 'Uruguay', club: 'Peñarol', attributes: { pace: 60, shooting: 64, passing: 50, dribbling: 58, defending: 32, physical: 72 } },
  { id: 'marchiori', name: 'Tomás Marchiori', overall: 71, position: 'GK', nationality: 'Argentina', club: 'Vélez', attributes: { pace: 70, shooting: 69, passing: 65, dribbling: 72, defending: 36, physical: 68 } },
  { id: 'medina-a', name: 'Agustín Medina', overall: 69, position: 'GK', nationality: 'Ecuador', club: 'Ind. del Valle', attributes: { pace: 68, shooting: 67, passing: 63, dribbling: 70, defending: 35, physical: 65 } },
  { id: 'mele', name: 'Santiago Mele', overall: 74, position: 'GK', nationality: 'Uruguay', club: 'Junior', attributes: { pace: 75, shooting: 73, passing: 68, dribbling: 76, defending: 40, physical: 72 } },
  { id: 'aguerre', name: 'Washington Aguerre', overall: 73, position: 'GK', nationality: 'Uruguay', club: 'Peñarol', attributes: { pace: 74, shooting: 72, passing: 66, dribbling: 75, defending: 39, physical: 71 } },
  { id: 'bava', name: 'Jorge Bava', overall: 68, position: 'GK', nationality: 'Uruguay', club: 'Nacional', attributes: { pace: 66, shooting: 65, passing: 61, dribbling: 68, defending: 34, physical: 63 } },
  { id: 'cleiton', name: 'Cleiton', overall: 74, position: 'GK', nationality: 'Brazil', club: 'Bragantino', attributes: { pace: 73, shooting: 72, passing: 71, dribbling: 75, defending: 42, physical: 73 } },
  { id: 'farinez-l', name: 'L. Fariñez', overall: 67, position: 'GK', nationality: 'Venezuela', club: 'Caracas', attributes: { pace: 68, shooting: 66, passing: 61, dribbling: 69, defending: 35, physical: 64 } },
  { id: 'valentini', name: 'Nicolás Valentini', overall: 73, position: 'DF', nationality: 'Argentina', club: 'Boca Juniors', attributes: { pace: 68, shooting: 38, passing: 58, dribbling: 56, defending: 74, physical: 76 } },
  { id: 'lollo-l', name: 'L. Lollo', overall: 70, position: 'DF', nationality: 'Argentina', club: 'Estudiantes', attributes: { pace: 50, shooting: 40, passing: 56, dribbling: 52, defending: 71, physical: 73 } },
  { id: 'alexsander', name: 'Alexsander', overall: 72, position: 'DF', nationality: 'Brazil', club: 'Fluminense', attributes: { pace: 76, shooting: 54, passing: 69, dribbling: 71, defending: 70, physical: 68 } },
  { id: 'huerta', name: 'Valber Huerta', overall: 72, position: 'DF', nationality: 'Chile', club: 'U. Católica', attributes: { pace: 64, shooting: 36, passing: 61, dribbling: 58, defending: 73, physical: 72 } },
  { id: 'kaiky', name: 'Kaiky', overall: 71, position: 'DF', nationality: 'Brazil', club: 'Almería', attributes: { pace: 67, shooting: 35, passing: 56, dribbling: 55, defending: 72, physical: 70 } },
  { id: 'olivera', name: 'Maximilian Olivera', overall: 72, position: 'DF', nationality: 'Uruguay', club: 'Peñarol', attributes: { pace: 71, shooting: 48, passing: 63, dribbling: 61, defending: 71, physical: 73 } },
  { id: 'falcon', name: 'Maximiliano Falcón', overall: 73, position: 'DF', nationality: 'Uruguay', club: 'Colo-Colo', attributes: { pace: 70, shooting: 40, passing: 58, dribbling: 59, defending: 73, physical: 79 } },
  { id: 'araujo-m', name: 'M. Araújo', overall: 68, position: 'DF', nationality: 'Uruguay', club: 'Nacional', attributes: { pace: 68, shooting: 34, passing: 54, dribbling: 52, defending: 68, physical: 70 } },
  { id: 'boselli-s', name: 'S. Boselli', overall: 73, position: 'DF', nationality: 'Uruguay', club: 'River Plate', attributes: { pace: 72, shooting: 39, passing: 60, dribbling: 58, defending: 74, physical: 75 } },
  { id: 'luan', name: 'Luan', overall: 74, position: 'DF', nationality: 'Brazil', club: 'Palmeiras', attributes: { pace: 65, shooting: 44, passing: 68, dribbling: 62, defending: 75, physical: 74 } },
  { id: 'murillo', name: 'Murillo', overall: 73, position: 'DF', nationality: 'Brazil', club: 'Corinthians', attributes: { pace: 72, shooting: 38, passing: 58, dribbling: 60, defending: 73, physical: 75 } },
  { id: 'noguera', name: 'Fabian Noguera', overall: 70, position: 'DF', nationality: 'Argentina', club: 'Nacional', attributes: { pace: 51, shooting: 42, passing: 52, dribbling: 50, defending: 71, physical: 77 } },
  { id: 'zaracho', name: 'Matías Zaracho', overall: 74, position: 'MF', nationality: 'Argentina', club: 'Atlético Mineiro', attributes: { pace: 78, shooting: 71, passing: 73, dribbling: 76, defending: 65, physical: 71 } },
  { id: 'menino', name: 'Gabriel Menino', overall: 73, position: 'MF', nationality: 'Brazil', club: 'Palmeiras', attributes: { pace: 73, shooting: 71, passing: 73, dribbling: 72, defending: 66, physical: 72 } },
  { id: 'sornoza', name: 'Junior Sornoza', overall: 74, position: 'MF', nationality: 'Ecuador', club: 'Ind. del Valle', attributes: { pace: 68, shooting: 73, passing: 78, dribbling: 75, defending: 50, physical: 63 } },
  { id: 'delacruz-h', name: 'H. De La Cruz', overall: 68, position: 'MF', nationality: 'Uruguay', club: 'Nacional', attributes: { pace: 70, shooting: 62, passing: 69, dribbling: 68, defending: 58, physical: 65 } },
  { id: 'fuentes', name: 'J. P. Fuentes', overall: 66, position: 'MF', nationality: 'Chile', club: 'Huachipato', attributes: { pace: 65, shooting: 58, passing: 64, dribbling: 63, defending: 61, physical: 67 } },
  { id: 'diaz-d', name: 'Damián Díaz', overall: 73, position: 'MF', nationality: 'Argentina', club: 'Barcelona SC', attributes: { pace: 60, shooting: 72, passing: 77, dribbling: 75, defending: 42, physical: 60 } },
  { id: 'pulgar', name: 'Erick Pulgar', overall: 75, position: 'MF', nationality: 'Chile', club: 'Flamengo', attributes: { pace: 68, shooting: 69, passing: 75, dribbling: 71, defending: 74, physical: 76 } },
  { id: 'campuzano', name: 'Jorman Campuzano', overall: 72, position: 'MF', nationality: 'Colombia', club: 'Boca Juniors', attributes: { pace: 70, shooting: 55, passing: 68, dribbling: 69, defending: 70, physical: 71 } },
  { id: 'alisson', name: 'Alisson', overall: 74, position: 'MF', nationality: 'São Paulo', club: 'São Paulo', attributes: { pace: 75, shooting: 68, passing: 72, dribbling: 74, defending: 68, physical: 72 } },
  { id: 'carneiro', name: 'Gonzalo Carneiro', overall: 72, position: 'FW', nationality: 'Uruguay', club: 'Nacional', attributes: { pace: 74, shooting: 72, passing: 62, dribbling: 70, defending: 35, physical: 78 } },
  { id: 'osorio-d', name: 'Darío Osorio', overall: 72, position: 'FW', nationality: 'Chile', club: 'U. de Chile', attributes: { pace: 79, shooting: 71, passing: 66, dribbling: 73, defending: 34, physical: 64 } },
  { id: 'arce-a', name: 'Alex Arce', overall: 73, position: 'FW', nationality: 'Paraguay', club: 'LDU Quito', attributes: { pace: 72, shooting: 75, passing: 61, dribbling: 68, defending: 30, physical: 74 } },
  { id: 'rondon', name: 'Salomón Rondón', overall: 74, position: 'FW', nationality: 'Venezuela', club: 'Pachuca', attributes: { pace: 68, shooting: 76, passing: 65, dribbling: 69, defending: 35, physical: 80 } },
  { id: 'mastantuono', name: 'Franco Mastantuono', overall: 73, position: 'FW', nationality: 'Argentina', club: 'River Plate', attributes: { pace: 77, shooting: 71, passing: 72, dribbling: 76, defending: 38, physical: 60 } },
  { id: 'estupinan', name: 'Estupiñán', overall: 68, position: 'FW', nationality: 'Ecuador', club: 'LDU Quito', attributes: { pace: 74, shooting: 67, passing: 58, dribbling: 66, defending: 30, physical: 70 } },
  { id: 'rodriguez-l', name: 'L. Rodríguez', overall: 67, position: 'FW', nationality: 'Argentina', club: 'Gimnasia', attributes: { pace: 72, shooting: 66, passing: 59, dribbling: 67, defending: 31, physical: 65 } },
  { id: 'candia', name: 'J. Candia', overall: 65, position: 'FW', nationality: 'Paraguay', club: 'Cerro Porteño', attributes: { pace: 68, shooting: 64, passing: 55, dribbling: 62, defending: 30, physical: 63 } }
];

export const marketPlayers: Player[] = rawPlayers.map(p => ({
  ...p,
  position: p.position as PlayerPosition,
  price: calculatePlayerPrice(p.overall)
}));
