import { OpponentTeam } from '@/types/game';

export const opponentTeams: OpponentTeam[] = [
  { id: 'flamengo', name: 'Flamengo', tier: 'very_good', country: 'Brazil', attackOverall: 84, defenseOverall: 83, teamChemistry: 92, logoColor: 'bg-red-600' },
  { id: 'palmeiras', name: 'Palmeiras', tier: 'very_good', country: 'Brazil', attackOverall: 83, defenseOverall: 83, teamChemistry: 90, logoColor: 'bg-green-600' },
  { id: 'river_plate', name: 'River Plate', tier: 'good', country: 'Argentina', attackOverall: 81, defenseOverall: 80, teamChemistry: 85, logoColor: 'bg-red-500' },
  { id: 'boca_juniors', name: 'Boca Juniors', tier: 'good', country: 'Argentina', attackOverall: 80, defenseOverall: 79, teamChemistry: 85, logoColor: 'bg-blue-600' },
  { id: 'botafogo', name: 'Botafogo', tier: 'good', country: 'Brazil', attackOverall: 82, defenseOverall: 78, teamChemistry: 84, logoColor: 'bg-slate-700' },
  { id: 'fluminense', name: 'Fluminense', tier: 'good', country: 'Brazil', attackOverall: 81, defenseOverall: 80, teamChemistry: 83, logoColor: 'bg-teal-700' },
  { id: 'atletico_mineiro', name: 'Atlético Mineiro', tier: 'good', country: 'Brazil', attackOverall: 80, defenseOverall: 79, teamChemistry: 84, logoColor: 'bg-slate-800' },
  { id: 'internacional', name: 'Internacional', tier: 'good', country: 'Brazil', attackOverall: 81, defenseOverall: 80, teamChemistry: 82, logoColor: 'bg-red-700' },
  { id: 'sao_paulo', name: 'São Paulo', tier: 'medium', country: 'Brazil', attackOverall: 78, defenseOverall: 77, teamChemistry: 78, logoColor: 'bg-red-800' },
  { id: 'corinthians', name: 'Corinthians', tier: 'medium', country: 'Brazil', attackOverall: 77, defenseOverall: 76, teamChemistry: 77, logoColor: 'bg-slate-900' },
  { id: 'penarol', name: 'Peñarol', tier: 'medium', country: 'Uruguay', attackOverall: 76, defenseOverall: 76, teamChemistry: 78, logoColor: 'bg-yellow-600' },
  { id: 'nacional', name: 'Nacional', tier: 'medium', country: 'Uruguay', attackOverall: 75, defenseOverall: 74, teamChemistry: 76, logoColor: 'bg-blue-700' },
  { id: 'colo_colo', name: 'Colo-Colo', tier: 'medium', country: 'Chile', attackOverall: 75, defenseOverall: 75, teamChemistry: 76, logoColor: 'bg-slate-100' },
  { id: 'idv', name: 'Ind. del Valle', tier: 'medium', country: 'Ecuador', attackOverall: 76, defenseOverall: 75, teamChemistry: 78, logoColor: 'bg-indigo-950' },
  { id: 'ldu', name: 'LDU Quito', tier: 'medium', country: 'Ecuador', attackOverall: 75, defenseOverall: 74, teamChemistry: 76, logoColor: 'bg-slate-300' },
  { id: 'estudiantes', name: 'Estudiantes', tier: 'medium', country: 'Argentina', attackOverall: 74, defenseOverall: 74, teamChemistry: 77, logoColor: 'bg-red-900' },
  { id: 'athletico_pr', name: 'Athletico PR', tier: 'medium', country: 'Brazil', attackOverall: 76, defenseOverall: 75, teamChemistry: 76, logoColor: 'bg-red-950' },
  { id: 'junior', name: 'Junior', tier: 'medium', country: 'Colombia', attackOverall: 74, defenseOverall: 73, teamChemistry: 75, logoColor: 'bg-red-500' },
  { id: 'olimpia', name: 'Olimpia', tier: 'medium', country: 'Paraguay', attackOverall: 75, defenseOverall: 74, teamChemistry: 76, logoColor: 'bg-slate-800' },
  { id: 'libertad', name: 'Libertad', tier: 'medium', country: 'Paraguay', attackOverall: 74, defenseOverall: 73, teamChemistry: 75, logoColor: 'bg-black' },
  { id: 'bolivar', name: 'Bolívar', tier: 'bad', country: 'Bolivia', attackOverall: 66, defenseOverall: 65, teamChemistry: 67, logoColor: 'bg-sky-500' },
  { id: 'the_strongest', name: 'The Strongest', tier: 'bad', country: 'Bolivia', attackOverall: 65, defenseOverall: 65, teamChemistry: 65, logoColor: 'bg-yellow-500' },
  { id: 'universitario', name: 'Universitario', tier: 'bad', country: 'Peru', attackOverall: 68, defenseOverall: 67, teamChemistry: 69, logoColor: 'bg-amber-100' },
  { id: 'alianza_lima', name: 'Alianza Lima', tier: 'bad', country: 'Peru', attackOverall: 67, defenseOverall: 67, teamChemistry: 68, logoColor: 'bg-blue-900' },
  { id: 'huachipato', name: 'Huachipato', tier: 'bad', country: 'Chile', attackOverall: 65, defenseOverall: 64, teamChemistry: 65, logoColor: 'bg-blue-800' },
  { id: 'caracas', name: 'Caracas FC', tier: 'bad', country: 'Venezuela', attackOverall: 63, defenseOverall: 63, teamChemistry: 64, logoColor: 'bg-red-950' },
  { id: 'tachira', name: 'Deportivo Táchira', tier: 'bad', country: 'Venezuela', attackOverall: 64, defenseOverall: 63, teamChemistry: 65, logoColor: 'bg-yellow-600' },
  { id: 'cerro_porteno', name: 'Cerro Porteño', tier: 'bad', country: 'Paraguay', attackOverall: 68, defenseOverall: 67, teamChemistry: 68, logoColor: 'bg-blue-700' },
  { id: 'millonarios', name: 'Millonarios', tier: 'bad', country: 'Colombia', attackOverall: 68, defenseOverall: 68, teamChemistry: 69, logoColor: 'bg-blue-600' },
  { id: 'liverpool', name: 'Liverpool', tier: 'bad', country: 'Uruguay', attackOverall: 64, defenseOverall: 63, teamChemistry: 64, logoColor: 'bg-blue-950' },
  { id: 'cobresal', name: 'Cobresal', tier: 'bad', country: 'Chile', attackOverall: 63, defenseOverall: 62, teamChemistry: 63, logoColor: 'bg-orange-600' },
  { id: 'barcelona_sc', name: 'Barcelona SC', tier: 'bad', country: 'Ecuador', attackOverall: 69, defenseOverall: 68, teamChemistry: 70, logoColor: 'bg-yellow-500' }
];
